"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "he" | "en" | "el" | "ru" | "ar";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
  dir: "rtl" | "ltr";
}

const elTranslations: Record<string, string> = {
  "nav.home": "Αρχική",
  "nav.properties": "Ακίνητα",
  "nav.countries": "Χώρες",
  "nav.howItWorks": "Πώς λειτουργεί",
  "nav.contact": "Επικοινωνία",
  "nav.browseInvestments": "Αναζήτηση",
  "nav.signIn": "Σύνδεση",
  "nav.signOut": "Αποσύνδεση",
  "nav.admin": "Διαχείριση",
  "nav.favorites": "Αγαπημένα",
  "nav.calculator": "Υπολογιστής",
  "nav.blog": "Blog",
  "nav.about": "Σχετικά",
  "nav.compare": "Σύγκριση",
  "nav.dashboard": "Dashboard",
  "nav.notifications": "Ειδοποιήσεις",
  "auth.signIn": "Σύνδεση",
  "auth.signUp": "Εγγραφή",
  "auth.signOut": "Αποσύνδεση",
  "auth.password": "Κωδικός",
  "auth.passwordPlaceholder": "Τουλάχιστον 6 χαρακτήρες",
  "auth.pleaseWait": "Παρακαλώ περιμένετε...",
  "auth.hasAccount": "Έχετε λογαριασμό;",
  "auth.noAccount": "Δεν έχετε λογαριασμό;",
  "auth.checkEmail": "Ελέγξτε το email σας",
  "form.name": "Όνομα",
  "form.namePlaceholder": "Πλήρες όνομα",
  "form.email": "Email",
  "form.emailPlaceholder": "your@email.com",
  "form.phone": "Τηλέφωνο",
  "form.phonePlaceholder": "+30...",
  "form.budget": "Προϋπολογισμός",
  "form.budgetPlaceholder": "Επιλέξτε εύρος",
  "form.message": "Μήνυμα",
  "form.error": "Κάτι πήγε στραβά. Δοκιμάστε ξανά.",
  "form.thankYou": "Ευχαριστούμε!",
  "form.thankYouSub": "Η αίτησή σας υποβλήθηκε.",
  "countries.title": "Χώρες Επένδυσης",
  "countries.subtitle": "Ανακαλύψτε ευκαιρίες σε κορυφαίες αγορές",
  "countries.available": "διαθέσιμα",
  "countries.backToCountries": "Πίσω στις χώρες",
  "countries.notFound": "Χώρα δεν βρέθηκε",
  "properties.property": "ακίνητο",
  "properties.propertiesNoun": "ακίνητα",
  "footer.quickLinks": "Γρήγοροι Σύνδεσμοι",
  "footer.investmentCountries": "Χώρες Επένδυσης",
  "footer.contact": "Επικοινωνία",
  "footer.greece": "Ελλάδα",
  "footer.cyprus": "Κύπρος",
  "footer.georgia": "Γεωργία",
  "footer.portugal": "Πορτογαλία",
  "footer.rights": "Με επιφύλαξη παντός δικαιώματος.",
  "footer.privacy": "Πολιτική Απορρήτου",
  "footer.terms": "Όροι Χρήσης",
  "notifications.markAllRead": "Σήμανση ως αναγνωσμένα",
  "notifications.empty": "Δεν υπάρχουν ειδοποιήσεις",
  "propertyType.apartment": "Διαμέρισμα",
  "propertyType.villa": "Βίλα",
  "propertyType.condo": "Κατοικία",
  "propertyType.studio": "Στούντιο",
  "propertyType.penthouse": "Πεντχάους",
  "propertyType.house": "Κατοικία",
  "propertyType.land": "Οικόπεδο",
  "card.price": "Τιμή",
};

const ruTranslations: Record<string, string> = {
  "nav.home": "Главная",
  "nav.properties": "Объекты",
  "nav.countries": "Страны",
  "nav.howItWorks": "Как это работает",
  "nav.contact": "Контакты",
  "nav.browseInvestments": "Просмотр",
  "nav.signIn": "Войти",
  "nav.signOut": "Выйти",
  "nav.admin": "Админ",
  "nav.favorites": "Избранное",
  "nav.calculator": "Калькулятор",
  "nav.blog": "Блог",
  "nav.about": "О нас",
  "nav.compare": "Сравнение",
  "nav.dashboard": "Панель",
  "nav.notifications": "Уведомления",
  "auth.signIn": "Войти",
  "auth.signUp": "Регистрация",
  "auth.signOut": "Выйти",
  "auth.password": "Пароль",
  "auth.passwordPlaceholder": "Минимум 6 символов",
  "auth.pleaseWait": "Пожалуйста, подождите...",
  "auth.hasAccount": "Уже есть аккаунт?",
  "auth.noAccount": "Нет аккаунта?",
  "auth.checkEmail": "Проверьте свой email",
  "form.name": "Имя",
  "form.namePlaceholder": "Полное имя",
  "form.email": "Email",
  "form.emailPlaceholder": "your@email.com",
  "form.phone": "Телефон",
  "form.phonePlaceholder": "+7...",
  "form.budget": "Бюджет",
  "form.budgetPlaceholder": "Выберите диапазон",
  "form.message": "Сообщение",
  "form.error": "Что-то пошло не так. Попробуйте ещё раз.",
  "form.thankYou": "Спасибо!",
  "form.thankYouSub": "Ваша заявка отправлена.",
  "countries.title": "Страны для инвестиций",
  "countries.subtitle": "Откройте возможности на лучших рынках",
  "countries.available": "доступно",
  "countries.backToCountries": "Назад к странам",
  "countries.notFound": "Страна не найдена",
  "properties.property": "объект",
  "properties.propertiesNoun": "объектов",
  "footer.quickLinks": "Быстрые ссылки",
  "footer.investmentCountries": "Страны инвестиций",
  "footer.contact": "Контакты",
  "footer.greece": "Греция",
  "footer.cyprus": "Кипр",
  "footer.georgia": "Грузия",
  "footer.portugal": "Португалия",
  "footer.rights": "Все права защищены.",
  "footer.privacy": "Политика конфиденциальности",
  "footer.terms": "Условия использования",
  "notifications.markAllRead": "Отметить все как прочитанные",
  "notifications.empty": "Нет уведомлений",
  "propertyType.apartment": "Квартира",
  "propertyType.villa": "Вилла",
  "propertyType.condo": "Кондо",
  "propertyType.studio": "Студия",
  "propertyType.penthouse": "Пентхаус",
  "propertyType.house": "Дом",
  "propertyType.land": "Участок",
  "card.price": "Цена",
};

const arTranslations: Record<string, string> = {
  "nav.home": "الرئيسية",
  "nav.properties": "العقارات",
  "nav.countries": "الدول",
  "nav.howItWorks": "كيف يعمل",
  "nav.contact": "اتصل بنا",
  "nav.browseInvestments": "تصفح",
  "nav.signIn": "تسجيل الدخول",
  "nav.signOut": "تسجيل الخروج",
  "nav.admin": "الإدارة",
  "nav.favorites": "المفضلة",
  "nav.calculator": "الحاسبة",
  "nav.blog": "المدونة",
  "nav.about": "عن الموقع",
  "nav.compare": "مقارنة",
  "nav.dashboard": "لوحة التحكم",
  "nav.notifications": "الإشعارات",
  "auth.signIn": "تسجيل الدخول",
  "auth.signUp": "إنشاء حساب",
  "auth.signOut": "تسجيل الخروج",
  "auth.password": "كلمة المرور",
  "auth.passwordPlaceholder": "6 أحرف على الأقل",
  "auth.pleaseWait": "يرجى الانتظار...",
  "auth.hasAccount": "لديك حساب بالفعل؟",
  "auth.noAccount": "ليس لديك حساب؟",
  "auth.checkEmail": "تحقق من بريدك الإلكتروني",
  "form.name": "الاسم",
  "form.namePlaceholder": "الاسم الكامل",
  "form.email": "البريد الإلكتروني",
  "form.emailPlaceholder": "your@email.com",
  "form.phone": "الهاتف",
  "form.phonePlaceholder": "+971...",
  "form.budget": "الميزانية",
  "form.budgetPlaceholder": "اختر النطاق",
  "form.message": "الرسالة",
  "form.error": "حدث خطأ ما. حاول مرة أخرى.",
  "form.thankYou": "شكراً!",
  "form.thankYouSub": "تم إرسال طلبك بنجاح.",
  "countries.title": "دول الاستثمار",
  "countries.subtitle": "اكتشف الفرص في أفضل الأسواق",
  "countries.available": "متاح",
  "countries.backToCountries": "العودة إلى الدول",
  "countries.notFound": "الدولة غير موجودة",
  "properties.property": "عقار",
  "properties.propertiesNoun": "عقارات",
  "footer.quickLinks": "روابط سريعة",
  "footer.investmentCountries": "دول الاستثمار",
  "footer.contact": "اتصل بنا",
  "footer.greece": "اليونان",
  "footer.cyprus": "قبرص",
  "footer.georgia": "جورجيا",
  "footer.portugal": "البرتغال",
  "footer.rights": "جميع الحقوق محفوظة.",
  "footer.privacy": "سياسة الخصوصية",
  "footer.terms": "شروط الاستخدام",
  "notifications.markAllRead": "تحديد الكل كمقروء",
  "notifications.empty": "لا توجد إشعارات",
  "propertyType.apartment": "شقة",
  "propertyType.villa": "فيلا",
  "propertyType.condo": "كوندو",
  "propertyType.studio": "استوديو",
  "propertyType.penthouse": "بنتهاوس",
  "propertyType.house": "منزل",
  "propertyType.land": "أرض",
  "card.price": "السعر",
};

const translations: Record<string, Record<string, string>> = {
  he: {
    // Navbar
    "nav.home": "ראשי",
    "nav.properties": "נכסים",
    "nav.countries": "מדינות",
    "nav.howItWorks": "איך זה עובד",
    "nav.contact": "צור קשר",
    "nav.browseInvestments": "עיין בהשקעות",
    "nav.signIn": "התחברות",
    "nav.signOut": "התנתקות",
    "nav.admin": "ניהול",
    "nav.favorites": "מועדפים",

    // Home
    "home.hero.badge": "השקעות נדל\"ן בינלאומיות",
    "home.hero.title": "השקעות נדל\"ן גלובליות למשקיעים ישראלים",
    "home.hero.subtitle": "גלו נכסי השקעה פרימיום בשווקים המובילים של אירופה. הזדמנויות שנבחרו בקפידה עם תמחור שקוף ותשואות גבוהות.",
    "home.search.country": "מדינה",
    "home.search.city": "עיר",
    "home.search.budget": "תקציב",
    "home.search.allCountries": "כל המדינות",
    "home.search.anyCity": "כל עיר",
    "home.search.anyBudget": "כל תקציב",
    "home.search.button": "חיפוש נכסים",
    "home.search.upTo": "עד",
    "home.stats.countries": "מדינות",
    "home.stats.properties": "נכסים",
    "home.stats.avgRoi": "תשואה ממוצעת",
    "home.stats.startingFrom": "החל מ-",
    "home.featured.title": "נכסי השקעה מומלצים",
    "home.featured.subtitle": "נכסים שנבחרו בקפידה עם פוטנציאל תשואה גבוה בשווקי הנדל\"ן המבטיחים ביותר באירופה.",
    "home.featured.browseAll": "עיין בכל ההשקעות",
    "home.howItWorks.title": "איך MANAIO עובד",
    "home.howItWorks.subtitle": "תהליך פשוט ושקוף מגילוי הנכס ועד השלמת ההשקעה.",
    "home.howItWorks.step": "שלב",
    "home.steps.browse.title": "עיון בנכסים",
    "home.steps.browse.desc": "חקרו הזדמנויות נדל\"ן בינלאומיות באזורי השקעה מובילים.",
    "home.steps.request.title": "בקשת פרטים",
    "home.steps.request.desc": "הגישו עניין וקבלו חבילת השקעה מקיפה עם כל הפרטים.",
    "home.steps.consult.title": "ייעוץ מומחים",
    "home.steps.consult.desc": "התחברו עם מומחי ההשקעות המקומיים שלנו לליווי אישי ובדיקת נאותות.",
    "home.steps.invest.title": "השקעה ורווח",
    "home.steps.invest.desc": "השלימו את ההשקעה עם ליווי משפטי מלא והתחילו להרוויח.",
    "home.countries.title": "מדינות השקעה",
    "home.countries.subtitle": "חקרו הזדמנויות נדל\"ן במדינות שנבחרו בקפידה.",
    "home.countries.properties": "נכסים",
    "home.cta.title": "מוכנים להתחיל להשקיע בחו\"ל?",
    "home.cta.subtitle": "הצטרפו למשקיעים ישראלים שכבר בונים עושר דרך נדל\"ן בינלאומי. עיינו במבחר הנכסים שלנו עוד היום.",
    "home.cta.button": "עיין בהשקעות",

    // Properties
    "properties.title": "נכסי השקעה",
    "properties.subtitle": "חקרו {count} נכסים נבחרים ב-4 מדינות",
    "properties.filter.country": "מדינה",
    "properties.filter.maxPrice": "מחיר מקסימלי",
    "properties.filter.type": "סוג נכס",
    "properties.filter.minRoi": "תשואה מינימלית",
    "properties.filter.bedrooms": "חדרים",
    "properties.filter.allCountries": "כל המדינות",
    "properties.filter.anyPrice": "כל מחיר",
    "properties.filter.allTypes": "כל הסוגים",
    "properties.filter.anyRoi": "כל תשואה",
    "properties.filter.any": "הכל",
    "properties.filter.clear": "נקה מסננים",
    "properties.filter.upTo": "עד",
    "properties.showing": "מציג {count} {noun}",
    "properties.property": "נכס",
    "properties.propertiesNoun": "נכסים",
    "properties.noResults": "אין נכסים התואמים למסננים",
    "properties.noResultsSub": "נסו לשנות את קריטריוני החיפוש",
    "properties.loading": "טוען נכסים...",

    // Property Card
    "card.roi": "תשואה",
    "card.bedroom": "חדר",
    "card.bedrooms": "חדרים",
    "card.cta": "לחץ לפרטים נוספים",

    // Property Details
    "detail.home": "ראשי",
    "detail.properties": "נכסים",
    "detail.expectedRoi": "תשואה צפויה",
    "detail.bedrooms": "חדרים",
    "detail.propertyType": "סוג נכס",
    "detail.country": "מדינה",
    "detail.about": "על הנכס",
    "detail.agent": "סוכן השקעות",
    "detail.requestDetails": "בקשת פרטי השקעה",
    "detail.formSubtitle": "מלאו את הטופס וצוות שלנו יחזור אליכם תוך 24 שעות.",

    // Lead Form
    "form.name": "שם מלא",
    "form.namePlaceholder": "השם המלא שלך",
    "form.email": "אימייל",
    "form.emailPlaceholder": "your@email.com",
    "form.phone": "טלפון",
    "form.phonePlaceholder": "+972...",
    "form.budget": "תקציב השקעה",
    "form.budgetPlaceholder": "בחר תקציב",
    "form.message": "הודעה",
    "form.messagePlaceholder": "ספרו לנו על יעדי ההשקעה שלכם...",
    "form.submit": "שלח בקשה",
    "form.submitting": "שולח...",
    "form.thankYou": "תודה רבה!",
    "form.thankYouSub": "הבקשה שלכם נשלחה. צוות ההשקעות שלנו ייצור איתכם קשר בקרוב.",
    "form.error": "משהו השתבש. אנא נסו שוב.",

    // Contact
    "contact.title": "צור קשר",
    "contact.subtitle": "דברו עם צוות ההשקעות שלנו",
    "contact.heading": "בואו נדבר על יעדי ההשקעה שלכם",
    "contact.description": "בין אם אתם משקיעים בינלאומיים חדשים או בוני תיקים מנוסים, הצוות שלנו כאן לעזור לכם לנווט הזדמנויות נדל\"ן גלובליות.",
    "contact.emailLabel": "אימייל",
    "contact.officeLabel": "משרד",
    "contact.office": "תל אביב, ישראל",
    "contact.hoursLabel": "שעות פעילות",
    "contact.hours": "ראשון - חמישי, 9:00 - 18:00",
    "contact.send": "שלח הודעה",
    "contact.sending": "שולח...",
    "contact.sent": "ההודעה נשלחה!",
    "contact.sentSub": "תודה שפניתם אלינו. נחזור אליכם תוך 24 שעות.",
    "contact.messagePlaceholder": "איך נוכל לעזור לכם?",

    // Countries
    "countries.title": "מדינות השקעה",
    "countries.subtitle": "חקרו הזדמנויות נדל\"ן במדינות שנבחרו בקפידה",
    "countries.investmentOverview": "סקירת השקעה",
    "countries.keyHighlights": "נקודות עיקריות",

    // How It Works
    "howItWorks.title": "איך זה עובד",
    "howItWorks.subtitle": "מדריך שלב אחר שלב להשקעה בנדל\"ן בינלאומי",
    "howItWorks.step1.title": "גלו הזדמנויות",
    "howItWorks.step2.title": "בקשו פרטים",
    "howItWorks.step3.title": "ייעוץ מומחים",
    "howItWorks.step4.title": "ליווי משפטי",
    "howItWorks.step5.title": "השלמת עסקה",
    "howItWorks.step6.title": "הרוויחו תשואות",
    "howItWorks.faq.title": "שאלות נפוצות",
    "howItWorks.cta": "עיין בהשקעות",

    // Favorites
    "favorites.title": "המועדפים שלי",
    "favorites.count": "{count} {noun} שמורים",
    "favorites.empty": "אין מועדפים עדיין",
    "favorites.emptySub": "עיינו בנכסים ולחצו על אייקון הלב כדי לשמור אותם",
    "favorites.browse": "עיון בנכסים",

    // Admin
    "admin.title": "ממשק ניהול",
    "admin.subtitle": "ניהול נכסים ({count} סה\"כ)",
    "admin.addNew": "הוסף נכס חדש",
    "admin.signInRequired": "יש להתחבר כדי לגשת לממשק הניהול",
    "admin.edit": "ערוך",
    "admin.delete": "מחק",
    "admin.deleteConfirm": "האם אתה בטוח שברצונך למחוק נכס זה?",
    "admin.addProperty": "הוסף נכס",
    "admin.editProperty": "ערוך נכס",
    "admin.updateProperty": "עדכן נכס",
    "admin.cancel": "ביטול",

    // Auth
    "auth.signIn": "התחברות",
    "auth.signUp": "הרשמה",
    "auth.createAccount": "יצירת חשבון",
    "auth.signInDesc": "התחברו כדי לגשת לנכסים השמורים ולחשבון שלכם",
    "auth.signUpDesc": "צרו חשבון כדי לשמור מועדפים ולעקוב אחר השקעות",
    "auth.password": "סיסמה",
    "auth.passwordPlaceholder": "מינימום 6 תווים",
    "auth.noAccount": "אין לכם חשבון?",
    "auth.hasAccount": "כבר יש לכם חשבון?",
    "auth.pleaseWait": "אנא המתינו...",
    "auth.checkEmail": "בדקו את האימייל שלכם לאישור החשבון.",
    "auth.accountType": "סוג חשבון",
    "auth.buyer": "משקיע",
    "auth.buyerDesc": "חיפוש נכסים להשקעה",
    "auth.agent": "סוכן",
    "auth.agentDesc": "פרסום וניהול נכסים",

    // Navbar extras
    "nav.about": "מי אנחנו",
    "nav.calculator": "מחשבון תשואה",
    "nav.blog": "בלוג",
    "nav.compare": "השוואת נכסים",
    "nav.dashboard": "אזור אישי",

    // Buyer Dashboard
    "dashboard.buyer.title": "האזור האישי שלי",
    "dashboard.buyer.welcome": "שלום",
    "dashboard.buyer.signInRequired": "יש להתחבר כדי לגשת לאזור האישי",
    "dashboard.buyer.favorites": "מועדפים",
    "dashboard.buyer.myRequests": "הבקשות שלי",
    "dashboard.buyer.account": "פרטי חשבון",
    "dashboard.buyer.savedProperties": "נכסים שמורים",
    "dashboard.buyer.requests": "בקשות",
    "dashboard.buyer.answered": "נענו",
    "dashboard.buyer.viewDetails": "פרטים",
    "dashboard.buyer.noRequests": "אין בקשות עדיין",
    "dashboard.buyer.noRequestsSub": "עיינו בנכסים ושלחו בקשת מידע",
    "dashboard.buyer.sendReminder": "שלח תזכורת",
    "dashboard.buyer.accountDetails": "פרטי חשבון",
    "dashboard.buyer.notifications": "הגדרות התראות",
    "dashboard.buyer.notifNewProperties": "נכסים חדשים שמתאימים לי",
    "dashboard.buyer.notifPriceChanges": "שינויי מחירים במועדפים",
    "dashboard.buyer.saved": "השינויים נשמרו!",
    "dashboard.buyer.saveChanges": "שמור שינויים",

    // Agent Dashboard
    "dashboard.agent.title": "פאנל סוכן",
    "dashboard.agent.welcome": "שלום",
    "dashboard.agent.signInRequired": "יש להתחבר כדי לגשת לפאנל הסוכן",
    "dashboard.agent.accessDenied": "גישה נדחתה",
    "dashboard.agent.agentsOnly": "רק סוכנים יכולים לגשת לעמוד זה",
    "dashboard.agent.myProperties": "הנכסים שלי",
    "dashboard.agent.leads": "לידים",
    "dashboard.agent.statistics": "סטטיסטיקות",
    "dashboard.agent.myProfile": "הפרופיל שלי",
    "dashboard.agent.activeProperties": "נכסים פעילים",
    "dashboard.agent.totalLeads": "סה\"כ לידים",
    "dashboard.agent.totalViews": "צפיות",
    "dashboard.agent.totalClicks": "לחיצות",
    "dashboard.agent.conversion": "המרה",
    "dashboard.agent.addProperty": "הוסף נכס",
    "dashboard.agent.editProperty": "ערוך נכס",
    "dashboard.agent.updateProperty": "עדכן נכס",
    "dashboard.agent.noProperties": "אין נכסים עדיין",
    "dashboard.agent.noPropertiesSub": "הוסיפו את הנכס הראשון שלכם",
    "dashboard.agent.noLeads": "אין לידים עדיין",
    "dashboard.agent.propTitle": "כותרת",
    "dashboard.agent.country": "מדינה",
    "dashboard.agent.city": "עיר",
    "dashboard.agent.price": "מחיר (€)",
    "dashboard.agent.roi": "תשואה (%)",
    "dashboard.agent.bedrooms": "חדרים",
    "dashboard.agent.propType": "סוג נכס",
    "dashboard.agent.featured": "נכס מומלץ",
    "dashboard.agent.description": "תיאור",
    "dashboard.agent.images": "קישורי תמונות (שורה לכל תמונה)",
    "dashboard.agent.location": "מיקום",
    "dashboard.agent.status": "סטטוס",
    "dashboard.agent.actions": "פעולות",
    "dashboard.agent.property": "נכס",
    "dashboard.agent.exportCSV": "ייצוא CSV",
    "dashboard.agent.propertyStats": "סטטיסטיקות לפי נכס",
    "dashboard.agent.views": "צפיות",
    "dashboard.agent.clicks": "לחיצות",
    "dashboard.agent.leadsCount": "לידים",
    "dashboard.agent.profileDetails": "פרטי סוכן",
    "dashboard.agent.companyName": "שם חברה",
    "dashboard.agent.companyUrl": "אתר חברה",

    // ROI Calculator
    "calculator.title": "מחשבון תשואת השקעה",
    "calculator.subtitle": "חשבו את התשואה הצפויה על השקעת הנדל\"ן שלכם",
    "calculator.parameters": "פרמטרים",
    "calculator.propertyPrice": "מחיר הנכס",
    "calculator.downPayment": "הון עצמי",
    "calculator.monthlyRent": "שכירות חודשית",
    "calculator.appreciation": "עליית ערך שנתית",
    "calculator.annualExpenses": "הוצאות שנתיות",
    "calculator.holdingPeriod": "תקופת החזקה",
    "calculator.years": "שנים",
    "calculator.monthlyIncome": "הכנסה חודשית נטו",
    "calculator.grossYield": "תשואה ברוטו",
    "calculator.netYield": "תשואה נטו",
    "calculator.totalROI": "תשואה כוללת",
    "calculator.summary": "סיכום",
    "calculator.totalInvestment": "סה\"כ השקעה",
    "calculator.totalRentalIncome": "הכנסות שכירות",
    "calculator.propertyAppreciation": "עליית ערך הנכס",
    "calculator.finalPropertyValue": "שווי הנכס הסופי",
    "calculator.totalProfit": "רווח כולל",
    "calculator.yearlyBreakdown": "פירוט שנתי",
    "calculator.year": "שנה",
    "calculator.propValue": "שווי נכס",
    "calculator.rentalIncome": "הכנסה שנתית",
    "calculator.cumIncome": "הכנסה מצטברת",
    "calculator.totalReturn": "תשואה כוללת",
    "calculator.disclaimer": "הערה: החישובים מבוססים על הנחות ואינם מהווים ייעוץ השקעות. התשואות בפועל עשויות להשתנות. יש להתייעץ עם מומחה לפני קבלת החלטות השקעה.",

    // About
    "about.title": "מי אנחנו - MANAIO",
    "about.subtitle": "אנחנו מחברים משקיעים ישראלים עם הזדמנויות נדל\"ן פרימיום ברחבי אירופה. עם ניסיון רב שנים וצוות מומחים מקומיים, אנו מציעים ליווי מקצועי לאורך כל תהליך ההשקעה.",
    "about.missionTitle": "המשימה שלנו",
    "about.missionText": "אנו מאמינים שכל משקיע ישראלי צריך גישה להזדמנויות נדל\"ן בינלאומיות ברמה הגבוהה ביותר. MANAIO נוסדה כדי לגשר על הפער בין משקיעים ישראלים לשווקי הנדל\"ן המבטיחים ביותר באירופה, תוך מתן שקיפות מלאה, ליווי מקצועי, וגישה להזדמנויות שבדרך כלל שמורות למשקיעים מוסדיים.",
    "about.whyTitle": "למה MANAIO?",
    "about.why1Title": "אמינות ושקיפות",
    "about.why1Desc": "כל נכס עובר בדיקת נאותות מקיפה. אנו מציגים נתונים אמיתיים ותשואות מבוססות שוק, ללא הבטחות מופרזות.",
    "about.why2Title": "מומחיות מקומית",
    "about.why2Desc": "צוות סוכנים מקומיים ב-4 מדינות שמכירים את השוק לעומק ומלווים אתכם בשפה שלכם.",
    "about.why3Title": "ליווי מקצה לקצה",
    "about.why3Desc": "מגילוי הנכס ועד סגירת העסקה - צוות משפטי, פיננסי וניהולי זמין עבורכם בכל שלב.",
    "about.teamTitle": "הצוות שלנו",
    "about.ctaTitle": "מוכנים להתחיל?",
    "about.ctaSubtitle": "צוות המומחים שלנו מחכה לעזור לכם למצוא את ההשקעה המושלמת.",

    // Blog
    "blog.title": "בלוג ומאמרים",
    "blog.subtitle": "מדריכים, טיפים ותובנות על השקעות נדל\"ן בינלאומיות",
    "blog.minRead": "דק' קריאה",
    "blog.readMore": "קראו עוד",
    "blog.noArticles": "אין מאמרים בקטגוריה זו",

    // Compare
    "compare.title": "השוואת נכסים",
    "compare.subtitle": "בחרו 2-3 נכסים והשוו ביניהם זה לצד זה",
    "compare.selectProperties": "בחרו נכסים להשוואה",
    "compare.searchPlaceholder": "חפשו נכס לפי שם, עיר או מדינה...",
    "compare.noResults": "לא נמצאו תוצאות",
    "compare.selectAtLeast": "בחרו לפחות 2 נכסים",
    "compare.selectAtLeastSub": "השתמשו בחיפוש למעלה כדי להוסיף נכסים להשוואה",
    "compare.price": "מחיר",
    "compare.location": "מיקום",
    "compare.roi": "תשואה צפויה",
    "compare.type": "סוג נכס",
    "compare.bedrooms": "חדרים",
    "compare.monthlyRent": "שכירות חודשית (אומדן)",
    "compare.annualIncome": "הכנסה שנתית (אומדן)",
    "compare.agent": "סוכן",
    "compare.viewProperty": "צפה בנכס",

    // How It Works (extended)
    "howItWorks.step1.desc": "עיינו באוסף הנכסים שלנו בשווקי הנדל\"ן המובילים באירופה. סננו לפי מדינה, סוג נכס, תקציב ותשואה צפויה כדי למצוא הזדמנויות שמתאימות ליעדי ההשקעה שלכם.",
    "howItWorks.step2.desc": "מצאתם נכס שמעניין אתכם? שלחו בקשה דרך טופס הפניות שלנו וקבלו חבילת השקעה מקיפה הכוללת תחזיות פיננסיות, דרישות משפטיות וניתוח שוק.",
    "howItWorks.step3.desc": "התחברו עם סוכני ההשקעות המנוסים שלנו המתמחים בשוק המקומי. הם ילוו אתכם בבדיקת נאותות, דרישות משפטיות, השלכות מס ויעזרו לכם לקבל החלטה מושכלת.",
    "howItWorks.step4.desc": "השותפים שלנו יסייעו בכל התיעוד המשפטי, בדיקות הנכס וההסדרים הפיננסיים. אנו עובדים עם עורכי דין ורואי חשבון מקומיים מהימנים.",
    "howItWorks.step5.desc": "השלימו את רכישת הנכס בשקיפות מלאה. הצוות שלנו מנהל את כל תהליך הסגירה, מחתימת חוזים ועד רישום הנכס והעברתו.",
    "howItWorks.step6.desc": "התחילו לייצר הכנסות משכירות או להנות מעליית ערך הנכס. שותפי ניהול הנכסים שלנו יכולים לטפל באיתור שוכרים, תחזוקה וניהול שוטף.",
    "howItWorks.faq1.q": "מי יכול להשקיע דרך MANAIO?",
    "howItWorks.faq1.a": "MANAIO מיועדת בעיקר למשקיעים ישראלים שמעוניינים לגוון את תיק ההשקעות שלהם עם נדל\"ן בינלאומי. עם זאת, הפלטפורמה שלנו פתוחה לכל משקיע מוסמך.",
    "howItWorks.faq2.q": "מה סכום ההשקעה המינימלי?",
    "howItWorks.faq2.a": "נכסים בפלטפורמה שלנו מתחילים מכ-€68,000 בגאורגיה, עם אפשרויות בכל טווחי התקציב ועד וילות פרימיום מעל €500,000.",
    "howItWorks.faq3.q": "האם צריך לבקר בנכס לפני ההשקעה?",
    "howItWorks.faq3.a": "למרות שאנו ממליצים לבקר כשזה אפשרי, רבים מהמשקיעים שלנו רוכשים מרחוק. אנו מספקים סיורים וירטואליים מפורטים, תיעוד מקיף ונציגים מקומיים שיכולים לבקר בשמכם.",
    "howItWorks.faq4.q": "איך מחושבים נתוני התשואה הצפויה?",
    "howItWorks.faq4.a": "תחזיות התשואה מבוססות על נתוני שכירות עדכניים, שיעורי תפוסה היסטוריים ועלויות ניהול נכסים. אלו הערכות והתשואות בפועל עשויות להשתנות בהתאם לתנאי השוק.",
    "howItWorks.ctaTitle": "מוכנים להתחיל?",
    "howItWorks.ctaSubtitle": "עיינו במבחר הנכסים הבינלאומיים שנבחרו בקפידה.",

    // Countries (extended)
    "countries.available": "זמינים",
    "countries.investIn": "השקעה ב",
    "countries.propertiesIn": "נכסים ב",
    "countries.noProperties": "אין נכסים זמינים ב{name} כרגע.",
    "countries.checkBack": "בדקו שוב בקרוב לרישומים חדשים.",
    "countries.notFound": "מדינה לא נמצאה",
    "countries.backToCountries": "חזרה למדינות",

    // Chat
    "chat.sendMessage": "שלח הודעה",
    "chat.placeholder": "כתבו הודעה...",
    "chat.noMessages": "אין הודעות עדיין. שלחו הודעה ראשונה!",
    "chat.loginRequired": "יש להתחבר כדי לשלוח הודעה",
    "chat.agentSubtitle": "סוכן השקעות",
    "chat.backToChats": "חזרה לצ'אטים",
    "chat.noChats": "אין צ'אטים עדיין",
    "chat.noChatsSub": "כאשר לקוחות ישלחו הודעות, הם יופיעו כאן",
    "dashboard.agent.chats": "צ'אטים",

    // Follow & Notifications
    "agent.follow": "עקוב",
    "agent.following": "עוקב",
    "nav.notifications": "התראות",
    "notifications.markAllRead": "סמן הכל כנקרא",
    "notifications.empty": "אין התראות",
    "dashboard.buyer.favoriteAgents": "מתווכים מועדפים",
    "dashboard.buyer.noAgents": "אין מתווכים מועדפים",
    "dashboard.buyer.noAgentsSub": "עקבו אחרי מתווכים מדפי הנכסים כדי לקבל התראות על מודעות חדשות",
    "dashboard.buyer.listings": "מודעות",
    "dashboard.buyer.unfollow": "הסר מעקב",

    // Footer
    "footer.soon": "בקרוב",

    // Navbar extras
    "nav.register": "הרשמה",
    "nav.myProperties": "הנכסים שלי",
    "auth.registerAsInvestor": "הרשמה כמשקיע",
    "auth.registerAsAgent": "הרשמה כסוכן",

    // Dashboard extras
    "dashboard.buyer.reminderSent": "תזכורת נשלחה לסוכן",

    // Chat
    "chat.agent": "סוכן",

    // About extras
    "about.aboutUs": "מי אנחנו",
    "about.foundersText": "מפתחי האתר רצו לאפשר פלטפורמה נוחה — לא רק לנדל\"ן בחו\"ל, אלא לכל עולם ההשקעות. זאת תוך הנגשת המתווכים הזרים והאופן שבו משקיעים בכל מדינה, כך שכל משקיע ישראלי יוכל לפעול בשוקי נדל\"ן בינלאומיים בביטחון, בשקיפות ובפשטות — בלי להתמצא מראש בכל שוק.",
    "about.stat.founded": "שנת הקמה",
    "about.stat.investments": "השקעות שהושלמו",
    "about.stat.investors": "משקיעים מרוצים",
    "about.stat.countries": "מדינות פעילות",

    // Countries extras
    "countries.comingSoon": "בקרוב",
    "countries.launchingSoon": "עומד לצאת בקרוב",
    "countries.stayTuned": "אנחנו עובדים על הבאת נכסי השקעה איכותיים במדינה זו. הישארו מעודכנים.",
    "countries.propertiesComingSoon": "נכסים ב{name} — בקרוב",

    // Property types
    "propertyType.apartment": "דירה",
    "propertyType.villa": "וילה",
    "propertyType.condo": "קונדו",
    "propertyType.studio": "סטודיו",
    "propertyType.penthouse": "פנטהאוס",
    "propertyType.house": "בית",
    "propertyType.land": "קרקע",

    // Card price label
    "card.price": "מחיר",

    // Admin tabs & stats
    "admin.tab.pendingAgents": "סוכנים ממתינים",
    "admin.tab.properties": "נכסים פעילים",
    "admin.tab.leads": "לידים",
    "admin.tab.closed": "נכסים סגורים",
    "admin.tab.agents": "סוכנים",
    "admin.tab.users": "משתמשים",
    "admin.tab.finance": "כספים",
    "admin.stat.activeProperties": "נכסים פעילים",
    "admin.stat.totalLeads": "סה\"כ לידים",
    "admin.stat.closedProperties": "נכסים סגורים",
    "admin.stat.agents": "סוכנים",
    "admin.accessDenied": "גישה נדחתה",
    "admin.accessDeniedSub": "אין לכם הרשאה לגשת לפאנל הניהול.",
    "admin.loading": "טוען...",
    "admin.connectedAs": "מחובר כ:",

    // Admin form
    "admin.form.editProperty": "עריכת נכס",
    "admin.form.addNewProperty": "הוספת נכס חדש",
    "admin.form.titleLabel": "כותרת",
    "admin.form.city": "עיר",
    "admin.form.expectedRoi": "תשואה צפויה (%)",
    "admin.form.bedrooms": "חדרי שינה",
    "admin.form.agentName": "שם סוכן",
    "admin.form.agentEmail": "אימייל סוכן",
    "admin.form.status": "סטטוס",
    "admin.form.statusActive": "פעיל",
    "admin.form.statusClosed": "סגור",
    "admin.form.premium": "⭐ נכס פרימיום",
    "admin.form.images": "תמונות הנכס",
    "admin.form.clickToSetPrimary": "(לחץ על תמונה להגדיר כראשית)",
    "admin.form.addImage": "הוסף תמונה",
    "admin.form.uploading": "מעלה...",
    "admin.table.property": "נכס",
    "admin.table.location": "מיקום",
    "admin.table.roi": "תשואה",
    "admin.table.type": "סוג",
    "admin.table.actions": "פעולות",
    "admin.table.edit": "עריכה",
    "admin.closeProperty": "סגור",
    "admin.reopenProperty": "פתח מחדש",
    "admin.noActiveProperties": "אין נכסים פעילים",
    "admin.noClosedProperties": "אין נכסים סגורים",

    // Footer
    "footer.description": "MANAIO מחברת משקיעים ישראלים עם הזדמנויות נדל\"ן בינלאומיות פרימיום. חקרו נכסים נבחרים בשווקים גלובליים מובילים עם תמחור שקוף וליווי מומחים.",
    "footer.quickLinks": "קישורים מהירים",
    "footer.investmentCountries": "מדינות השקעה",
    "footer.contact": "יצירת קשר",
    "footer.greece": "יוון",
    "footer.cyprus": "קפריסין",
    "footer.georgia": "גאורגיה",
    "footer.portugal": "פורטוגל",
    "footer.disclaimer": "הבהרה משפטית",
    "footer.disclaimerText": "MANAIO היא פלטפורמת מידע ואינה מספקת ייעוץ פיננסי, משפטי או מיסויי. כל החלטות ההשקעה צריכות להתקבל לאחר התייעצות עם אנשי מקצוע מוסמכים. ערכי נכסים, תשואות שכירות והערכות תשואה הם תחזיות המבוססות על נתוני שוק ואינם מובטחים. ביצועי עבר אינם מעידים על תוצאות עתידיות.",
    "footer.rights": "כל הזכויות שמורות.",
    "footer.privacy": "מדיניות פרטיות",
    "footer.terms": "תנאי שימוש",

    // Common
    "common.loading": "טוען...",
    "common.notFound": "העמוד לא נמצא",
    "common.pageNotFoundDesc": "מצטערים, העמוד שחיפשתם לא קיים או שהוסר. אולי תמצאו את מה שאתם מחפשים בעמודים הבאים:",
    "common.backToHome": "חזרה לדף הבית",
    "common.viewProperties": "צפו בנכסים",

    // Cookies
    "cookies.text": "אנו משתמשים בעוגיות לשיפור חוויית הגלישה ולניתוח תנועת האתר.",
    "cookies.accept": "אישור",
    "cookies.decline": "דחה",
    "cookies.privacy": "מדיניות הפרטיות",

    // Register Agent
    "register.agent.title": "הרשמה כסוכן נדל\"ן",
    "register.agent.subtitle": "צרו חשבון והתחילו לפרסם נכסים",
    "register.agent.pending": "הבקשה נשלחה לבדיקה",
    "register.agent.pendingDesc": "תודה על ההרשמה! הבקשה שלכם נמצאת בבדיקה על ידי צוות MANAIO. נחזור אליכם תוך 1-2 ימי עסקים לאחר אישור רישיון התיווך וחוזה השותפות.",
    "register.agent.questions": "שאלות? צרו קשר:",
    "register.agent.companyName": "שם חברה",
    "register.agent.companyNamePlaceholder": "שם החברה שלכם (לא חובה)",
    "register.agent.brokerLicense": "רישיון תיווך *",
    "register.agent.idCard": "תעודת זהות *",
    "register.agent.fileFormats": "PDF, JPG או PNG — עד 5MB",
    "register.agent.partnershipAgree": "קראתי ואני מסכים/ה לתנאי",
    "register.agent.partnershipName": "הסכם השותפות",
    "register.agent.partnershipWith": "עם חברת MANAIO",
    "register.agent.submit": "שלח בקשת הרשמה",
    "register.agent.investorLink": "משקיע? הירשמו כאן →",
    "register.agent.errorInvalidFileType": "סוג קובץ לא מורשה. יש להעלות PDF או תמונה (JPG/PNG)",
    "register.agent.errorInvalidExtension": "סיומת קובץ לא מורשית",
    "register.agent.errorFileTooLarge": "הקובץ גדול מדי. גודל מקסימלי: 5MB",
    "register.agent.errorNoLicense": "יש להעלות רישיון תיווך",
    "register.agent.errorNoId": "יש להעלות תעודת זהות",
    "register.agent.errorNoPartnership": "יש לאשר את הסכם השותפות",

    // Register Buyer
    "register.buyer.title": "הרשמה כמשקיע",
    "register.buyer.subtitle": "צרו חשבון וגלו הזדמנויות השקעה",
    "register.buyer.joinTitle": "הצטרפו כמשקיעים",
    "register.buyer.joinSubtitle": "גלו הזדמנויות השקעה בנדל\"ן בינלאומי עם ליווי מקצועי מקצה לקצה.",
    "register.buyer.benefit1": "גישה לנכסי השקעה פרימיום ב-4 מדינות",
    "register.buyer.benefit2": "שמירת נכסים מועדפים ומעקב אחריהם",
    "register.buyer.benefit3": "מעקב אחר בקשות מידע וסטטוס לידים",
    "register.buyer.benefit4": "התראות על נכסים חדשים ושינויי מחירים",
    "register.buyer.benefit5": "מחשבון תשואה והשוואת נכסים",
    "register.buyer.termsAgree": "קראתי ואני מסכים/ה ל",
    "register.buyer.terms": "תנאי השימוש",
    "register.buyer.termsAnd": "ול",
    "register.buyer.privacy": "מדיניות הפרטיות",
    "register.buyer.termsOf": "של MANAIO",
    "register.buyer.submit": "הרשמה כמשקיע",
    "register.buyer.agentLink": "סוכן נדל\"ן? הירשמו כאן →",
    "register.buyer.errorTerms": "יש לאשר את תנאי השימוש",

    // Properties search
    "properties.search": "חיפוש לפי עיר, מדינה, סוג נכס...",

    // Lead status labels
    "status.sent": "נשלח",
    "status.in_progress": "בטיפול",
    "status.answered": "נענה",
    "status.closed": "סגור",

    // Admin extended
    "admin.loadingLeads": "טוען לידים...",
    "admin.noLeads": "אין לידים עדיין",
    "admin.noAgents": "לא נמצאו סוכנים",
    "admin.missing": "חסר",
    "admin.pendingApproval": "ממתין לאישור",
    "admin.missingDocuments": "מסמכים חסרים",
    "admin.approve": "אשר",
    "admin.reject": "דחה",
    "admin.rejectConfirm": "האם אתה בטוח שברצונך לדחות סוכן זה?",
    "admin.brokerLicense": "רישיון תיווך",
    "admin.idCard": "תעודת זהות",
    "admin.partnershipAgreement": "הסכם שותפות",
    "admin.partnershipApproved": "אושר",
    "admin.notSigned": "לא נחתם",
    "admin.loadingUsers": "טוען משתמשים...",
    "admin.noUsers": "לא נמצאו משתמשים רשומים",
    "admin.loadingFinance": "טוען נתוני כספים...",
    "admin.pendingAgents.noPending": "אין בקשות סוכנים ממתינות",
    "admin.registered": "נרשם:",
    "admin.generalInquiry": "פנייה כללית",

    // Admin finance
    "admin.finance.totalCharged": "סה״כ חויב",
    "admin.finance.paid": "שולם",
    "admin.finance.pendingPayment": "ממתין לתשלום",
    "admin.finance.agentSummary": "סיכום לפי סוכן",
    "admin.finance.paymentDetails": "פירוט תשלומים",
    "admin.finance.exportCSV": "ייצוא CSV",
    "admin.finance.addPayment": "הוסף תשלום",
    "admin.finance.addPaymentTitle": "הוספת תשלום / עמלה",
    "admin.finance.agent": "סוכן",
    "admin.finance.selectAgent": "בחר סוכן...",
    "admin.finance.type": "סוג",
    "admin.finance.leadFee": "דמי ליד",
    "admin.finance.commission": "עמלה",
    "admin.finance.bonus": "בונוס",
    "admin.finance.amount": "סכום (₪)",
    "admin.finance.relatedLead": "ליד קשור (אופציונלי)",
    "admin.finance.noSpecificLead": "ללא ליד ספציפי",
    "admin.finance.notes": "הערות",
    "admin.finance.notesPlaceholder": "הערה כלשהי...",
    "admin.finance.saving": "שומר...",
    "admin.finance.noPayments": "אין תשלומים עדיין",
    "admin.finance.markPaid": "סמן כשולם",
    "admin.finance.pending": "ממתין",
    "admin.finance.leads": "לידים",
    "admin.finance.totalOwed": "סה״כ חויב",
    "admin.finance.balance": "יתרה",
    "admin.finance.deletePayment": "מחק",
    "admin.finance.deleteConfirm": "למחוק תשלום זה?",
    "admin.finance.amountLabel": "סכום",
    "admin.finance.status": "סטטוס",
    "admin.finance.notesCol": "הערות",
    "admin.finance.dateCol": "תאריך",
    "admin.finance.actionsCol": "פעולות",

    // Admin table headers
    "admin.leads.name": "שם",
    "admin.leads.email": "אימייל",
    "admin.leads.phone": "טלפון",
    "admin.leads.budget": "תקציב",
    "admin.leads.property": "נכס",
    "admin.leads.message": "הודעה",
    "admin.leads.date": "תאריך",
    "admin.agents.agent": "סוכן",
    "admin.agents.country": "מדינה",
    "admin.agents.city": "עיר",
    "admin.agents.properties": "נכסים",
    "admin.users.role": "תפקיד",
    "admin.users.joined": "הצטרף",

    // Dashboard agent form sections
    "dashboard.agent.basicDetails": "פרטים בסיסיים",
    "dashboard.agent.priceReturns": "מחיר ותשואה",
    "dashboard.agent.propertySpecs": "מפרט הנכס",
    "dashboard.agent.amenitiesLabel": "מתקנים ואביזרים",
    "dashboard.agent.neighborhood": "שכונה",
    "dashboard.agent.addExpectedRoi": "הוסף תשואה צפויה (%)",
    "dashboard.agent.bathrooms": "חדרי שירות",
    "dashboard.agent.areaSqm": "שטח (מ״ר)",
    "dashboard.agent.floor": "קומה",
    "dashboard.agent.yearBuilt": "שנת בנייה",
    "dashboard.agent.furnished": "מרוהט",
    "dashboard.agent.propertyImages": "תמונות הנכס",
    "dashboard.agent.clickToSetPrimary": "לחץ על תמונה כדי להגדיר אותה כראשית (כוכב = ראשית)",
    "dashboard.agent.addImageBtn": "הוסף תמונה",
    "dashboard.agent.imageFormats": "JPG, PNG, WEBP — ניתן לבחור מספר קבצים",
    "dashboard.agent.uploading": "מעלה תמונות...",
    "dashboard.agent.applicationReview": "הבקשה שלכם בבדיקה",
    "dashboard.agent.pendingDesc": "תודה על ההרשמה! צוות MANAIO בודק את רישיון התיווך שלכם ואת הסכם השותפות. תקבלו הודעה במייל לאחר אישור החשבון (בדרך כלל תוך 1-2 ימי עסקים).",
    "dashboard.agent.waitingApproval": "ממתין לאישור — הדף יתעדכן אוטומטית",
    "dashboard.agent.questions": "שאלות?",
  },

  en: {
    // Navbar
    "nav.home": "Home",
    "nav.properties": "Properties",
    "nav.countries": "Countries",
    "nav.howItWorks": "How it Works",
    "nav.contact": "Contact",
    "nav.browseInvestments": "Browse Investments",
    "nav.signIn": "Sign In",
    "nav.signOut": "Sign Out",
    "nav.admin": "Admin",
    "nav.favorites": "Favorites",

    // Home
    "home.hero.badge": "International Real Estate Investments",
    "home.hero.title": "Global Real Estate Investments for Israeli Investors",
    "home.hero.subtitle": "Discover premium investment properties in Europe's top markets. Expert-curated opportunities with transparent pricing and high returns.",
    "home.search.country": "Country",
    "home.search.city": "City",
    "home.search.budget": "Budget",
    "home.search.allCountries": "All Countries",
    "home.search.anyCity": "Any city",
    "home.search.anyBudget": "Any Budget",
    "home.search.button": "Search Properties",
    "home.search.upTo": "Up to",
    "home.stats.countries": "Countries",
    "home.stats.properties": "Properties",
    "home.stats.avgRoi": "Avg. ROI",
    "home.stats.startingFrom": "Starting From",
    "home.featured.title": "Featured Investment Properties",
    "home.featured.subtitle": "Hand-picked properties with strong ROI potential in Europe's most promising real estate markets.",
    "home.featured.browseAll": "Browse All Investments",
    "home.howItWorks.title": "How MANAIO Works",
    "home.howItWorks.subtitle": "A simple, transparent process from property discovery to investment completion.",
    "home.howItWorks.step": "STEP",
    "home.steps.browse.title": "Browse Properties",
    "home.steps.browse.desc": "Explore curated international real estate opportunities across top investment markets.",
    "home.steps.request.title": "Request Details",
    "home.steps.request.desc": "Submit your interest and receive a comprehensive investment package with all the details.",
    "home.steps.consult.title": "Expert Consultation",
    "home.steps.consult.desc": "Connect with our local investment experts for personalized guidance and due diligence.",
    "home.steps.invest.title": "Invest & Earn",
    "home.steps.invest.desc": "Complete your investment with full legal support and start earning returns.",
    "home.countries.title": "Investment Countries",
    "home.countries.subtitle": "Explore real estate opportunities in these carefully selected markets.",
    "home.countries.properties": "properties",
    "home.cta.title": "Ready to Start Investing Internationally?",
    "home.cta.subtitle": "Join Israeli investors who are already building wealth through international real estate. Browse our curated selection of properties today.",
    "home.cta.button": "Browse Investments",

    // Properties
    "properties.title": "Investment Properties",
    "properties.subtitle": "Explore {count} curated properties across 4 countries",
    "properties.filter.country": "Country",
    "properties.filter.maxPrice": "Max Price",
    "properties.filter.type": "Property Type",
    "properties.filter.minRoi": "Min ROI",
    "properties.filter.bedrooms": "Bedrooms",
    "properties.filter.allCountries": "All Countries",
    "properties.filter.anyPrice": "Any Price",
    "properties.filter.allTypes": "All Types",
    "properties.filter.anyRoi": "Any ROI",
    "properties.filter.any": "Any",
    "properties.filter.clear": "Clear Filters",
    "properties.filter.upTo": "Up to",
    "properties.showing": "Showing {count} {noun}",
    "properties.property": "property",
    "properties.propertiesNoun": "properties",
    "properties.noResults": "No properties match your filters",
    "properties.noResultsSub": "Try adjusting your search criteria",
    "properties.loading": "Loading properties...",

    // Property Card
    "card.roi": "ROI",
    "card.bedroom": "Bedroom",
    "card.bedrooms": "Bedrooms",
    "card.cta": "Click for More Details",

    // Property Details
    "detail.home": "Home",
    "detail.properties": "Properties",
    "detail.expectedRoi": "Expected ROI",
    "detail.bedrooms": "Bedrooms",
    "detail.propertyType": "Property Type",
    "detail.country": "Country",
    "detail.about": "About This Property",
    "detail.agent": "Investment Agent",
    "detail.requestDetails": "Request Investment Details",
    "detail.formSubtitle": "Fill out the form and our team will get back to you within 24 hours.",

    // Lead Form
    "form.name": "Full Name",
    "form.namePlaceholder": "Your full name",
    "form.email": "Email",
    "form.emailPlaceholder": "your@email.com",
    "form.phone": "Phone",
    "form.phonePlaceholder": "+972...",
    "form.budget": "Investment Budget",
    "form.budgetPlaceholder": "Select your budget",
    "form.message": "Message",
    "form.messagePlaceholder": "Tell us about your investment goals...",
    "form.submit": "Submit Request",
    "form.submitting": "Submitting...",
    "form.thankYou": "Thank You!",
    "form.thankYouSub": "Your request has been submitted. Our investment team will contact you shortly.",
    "form.error": "Something went wrong. Please try again.",

    // Contact
    "contact.title": "Contact Us",
    "contact.subtitle": "Get in touch with our investment team",
    "contact.heading": "Let's Discuss Your Investment Goals",
    "contact.description": "Whether you're a first-time international investor or an experienced portfolio builder, our team is here to help you navigate global real estate opportunities.",
    "contact.emailLabel": "Email",
    "contact.officeLabel": "Office",
    "contact.office": "Tel Aviv, Israel",
    "contact.hoursLabel": "Hours",
    "contact.hours": "Sunday - Thursday, 9:00 - 18:00 IST",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.sent": "Message Sent!",
    "contact.sentSub": "Thank you for reaching out. We'll get back to you within 24 hours.",
    "contact.messagePlaceholder": "How can we help you?",

    // Countries
    "countries.title": "Investment Countries",
    "countries.subtitle": "Explore real estate opportunities in these carefully selected markets",
    "countries.investmentOverview": "Investment Overview",
    "countries.keyHighlights": "Key Highlights",

    // How It Works
    "howItWorks.title": "How It Works",
    "howItWorks.subtitle": "A step-by-step guide to international real estate investment",
    "howItWorks.step1.title": "Discover Opportunities",
    "howItWorks.step2.title": "Request Details",
    "howItWorks.step3.title": "Expert Consultation",
    "howItWorks.step4.title": "Legal Setup",
    "howItWorks.step5.title": "Complete Purchase",
    "howItWorks.step6.title": "Earn Returns",
    "howItWorks.faq.title": "Frequently Asked Questions",
    "howItWorks.cta": "Browse Investments",

    // Favorites
    "favorites.title": "My Favorites",
    "favorites.count": "{count} saved {noun}",
    "favorites.empty": "No favorites yet",
    "favorites.emptySub": "Browse properties and click the heart icon to save them",
    "favorites.browse": "Browse Properties",

    // Admin
    "admin.title": "Admin Panel",
    "admin.subtitle": "Manage properties ({count} total)",
    "admin.addNew": "Add New Property",
    "admin.signInRequired": "Sign in to access the admin panel",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.deleteConfirm": "Are you sure you want to delete this property?",
    "admin.addProperty": "Add Property",
    "admin.editProperty": "Edit Property",
    "admin.updateProperty": "Update Property",
    "admin.cancel": "Cancel",

    // Auth
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.createAccount": "Create Account",
    "auth.signInDesc": "Sign in to access your saved properties and account",
    "auth.signUpDesc": "Create an account to save favorites and track investments",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "Minimum 6 characters",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.pleaseWait": "Please wait...",
    "auth.checkEmail": "Check your email to confirm your account.",
    "auth.accountType": "Account Type",
    "auth.buyer": "Investor",
    "auth.buyerDesc": "Search properties to invest",
    "auth.agent": "Agent",
    "auth.agentDesc": "List and manage properties",

    // Navbar extras
    "nav.about": "About",
    "nav.calculator": "ROI Calculator",
    "nav.blog": "Blog",
    "nav.compare": "Compare",
    "nav.dashboard": "Dashboard",

    // Buyer Dashboard
    "dashboard.buyer.title": "My Dashboard",
    "dashboard.buyer.welcome": "Welcome",
    "dashboard.buyer.signInRequired": "Sign in to access your dashboard",
    "dashboard.buyer.favorites": "Favorites",
    "dashboard.buyer.myRequests": "My Requests",
    "dashboard.buyer.account": "Account",
    "dashboard.buyer.savedProperties": "Saved Properties",
    "dashboard.buyer.requests": "Requests",
    "dashboard.buyer.answered": "Answered",
    "dashboard.buyer.viewDetails": "Details",
    "dashboard.buyer.noRequests": "No requests yet",
    "dashboard.buyer.noRequestsSub": "Browse properties and send an inquiry",
    "dashboard.buyer.sendReminder": "Send Reminder",
    "dashboard.buyer.accountDetails": "Account Details",
    "dashboard.buyer.notifications": "Notification Settings",
    "dashboard.buyer.notifNewProperties": "New properties matching my criteria",
    "dashboard.buyer.notifPriceChanges": "Price changes in favorites",
    "dashboard.buyer.saved": "Changes saved!",
    "dashboard.buyer.saveChanges": "Save Changes",

    // Agent Dashboard
    "dashboard.agent.title": "Agent Panel",
    "dashboard.agent.welcome": "Welcome",
    "dashboard.agent.signInRequired": "Sign in to access the agent panel",
    "dashboard.agent.accessDenied": "Access Denied",
    "dashboard.agent.agentsOnly": "Only agents can access this page",
    "dashboard.agent.myProperties": "My Properties",
    "dashboard.agent.leads": "Leads",
    "dashboard.agent.statistics": "Statistics",
    "dashboard.agent.myProfile": "My Profile",
    "dashboard.agent.activeProperties": "Active Properties",
    "dashboard.agent.totalLeads": "Total Leads",
    "dashboard.agent.totalViews": "Views",
    "dashboard.agent.totalClicks": "Clicks",
    "dashboard.agent.conversion": "Conversion",
    "dashboard.agent.addProperty": "Add Property",
    "dashboard.agent.editProperty": "Edit Property",
    "dashboard.agent.updateProperty": "Update Property",
    "dashboard.agent.noProperties": "No properties yet",
    "dashboard.agent.noPropertiesSub": "Add your first property",
    "dashboard.agent.noLeads": "No leads yet",
    "dashboard.agent.propTitle": "Title",
    "dashboard.agent.country": "Country",
    "dashboard.agent.city": "City",
    "dashboard.agent.price": "Price (€)",
    "dashboard.agent.roi": "ROI (%)",
    "dashboard.agent.bedrooms": "Bedrooms",
    "dashboard.agent.propType": "Property Type",
    "dashboard.agent.featured": "Featured Property",
    "dashboard.agent.description": "Description",
    "dashboard.agent.images": "Image URLs (one per line)",
    "dashboard.agent.location": "Location",
    "dashboard.agent.status": "Status",
    "dashboard.agent.actions": "Actions",
    "dashboard.agent.property": "Property",
    "dashboard.agent.exportCSV": "Export CSV",
    "dashboard.agent.propertyStats": "Statistics by Property",
    "dashboard.agent.views": "Views",
    "dashboard.agent.clicks": "Clicks",
    "dashboard.agent.leadsCount": "Leads",
    "dashboard.agent.profileDetails": "Agent Details",
    "dashboard.agent.companyName": "Company Name",
    "dashboard.agent.companyUrl": "Company Website",

    // ROI Calculator
    "calculator.title": "Investment ROI Calculator",
    "calculator.subtitle": "Calculate the expected return on your real estate investment",
    "calculator.parameters": "Parameters",
    "calculator.propertyPrice": "Property Price",
    "calculator.downPayment": "Down Payment",
    "calculator.monthlyRent": "Monthly Rent",
    "calculator.appreciation": "Annual Appreciation",
    "calculator.annualExpenses": "Annual Expenses",
    "calculator.holdingPeriod": "Holding Period",
    "calculator.years": "years",
    "calculator.monthlyIncome": "Monthly Net Income",
    "calculator.grossYield": "Gross Yield",
    "calculator.netYield": "Net Yield",
    "calculator.totalROI": "Total ROI",
    "calculator.summary": "Summary",
    "calculator.totalInvestment": "Total Investment",
    "calculator.totalRentalIncome": "Total Rental Income",
    "calculator.propertyAppreciation": "Property Appreciation",
    "calculator.finalPropertyValue": "Final Property Value",
    "calculator.totalProfit": "Total Profit",
    "calculator.yearlyBreakdown": "Yearly Breakdown",
    "calculator.year": "Year",
    "calculator.propValue": "Property Value",
    "calculator.rentalIncome": "Annual Income",
    "calculator.cumIncome": "Cumulative Income",
    "calculator.totalReturn": "Total Return",
    "calculator.disclaimer": "Note: Calculations are based on assumptions and do not constitute investment advice. Actual returns may vary. Consult a professional before making investment decisions.",

    // About
    "about.title": "About MANAIO",
    "about.subtitle": "We connect Israeli investors with premium real estate opportunities across Europe. With years of experience and a team of local experts, we offer professional guidance throughout the entire investment process.",
    "about.missionTitle": "Our Mission",
    "about.missionText": "We believe every Israeli investor deserves access to top-tier international real estate opportunities. MANAIO was founded to bridge the gap between Israeli investors and Europe's most promising real estate markets, providing full transparency, professional guidance, and access to opportunities typically reserved for institutional investors.",
    "about.whyTitle": "Why MANAIO?",
    "about.why1Title": "Trust & Transparency",
    "about.why1Desc": "Every property undergoes comprehensive due diligence. We present real data and market-based yields, without exaggerated promises.",
    "about.why2Title": "Local Expertise",
    "about.why2Desc": "A team of local agents across 4 countries who know the market inside out and guide you in your language.",
    "about.why3Title": "End-to-End Support",
    "about.why3Desc": "From property discovery to deal closing - legal, financial, and management teams available at every step.",
    "about.teamTitle": "Our Team",
    "about.ctaTitle": "Ready to Get Started?",
    "about.ctaSubtitle": "Our team of experts is waiting to help you find the perfect investment.",

    // Blog
    "blog.title": "Blog & Articles",
    "blog.subtitle": "Guides, tips and insights on international real estate investments",
    "blog.minRead": "min read",
    "blog.readMore": "Read More",
    "blog.noArticles": "No articles in this category",

    // Compare
    "compare.title": "Compare Properties",
    "compare.subtitle": "Select 2-3 properties and compare them side by side",
    "compare.selectProperties": "Select properties to compare",
    "compare.searchPlaceholder": "Search by name, city or country...",
    "compare.noResults": "No results found",
    "compare.selectAtLeast": "Select at least 2 properties",
    "compare.selectAtLeastSub": "Use the search above to add properties for comparison",
    "compare.price": "Price",
    "compare.location": "Location",
    "compare.roi": "Expected ROI",
    "compare.type": "Property Type",
    "compare.bedrooms": "Bedrooms",
    "compare.monthlyRent": "Monthly Rent (est.)",
    "compare.annualIncome": "Annual Income (est.)",
    "compare.agent": "Agent",
    "compare.viewProperty": "View Property",

    // How It Works (extended)
    "howItWorks.step1.desc": "Browse our curated marketplace of international real estate investments. Filter by country, property type, budget, and expected ROI to find opportunities that match your investment goals.",
    "howItWorks.step2.desc": "Found a property that interests you? Submit a request through our lead form to receive a comprehensive investment package, including financial projections, legal requirements, and market analysis.",
    "howItWorks.step3.desc": "Connect with our experienced investment agents who specialize in the local market. They will guide you through due diligence, legal requirements, tax implications, and help you make an informed decision.",
    "howItWorks.step4.desc": "Our partners will assist with all legal documentation, property inspections, and financial arrangements. We work with trusted local lawyers and accountants to ensure a smooth transaction.",
    "howItWorks.step5.desc": "Finalize your property purchase with full transparency. Our team manages the entire closing process, from signing contracts to property registration and handover.",
    "howItWorks.step6.desc": "Start generating rental income or benefit from property appreciation. Our property management partners can handle tenant sourcing, maintenance, and ongoing management on your behalf.",
    "howItWorks.faq1.q": "Who can invest through MANAIO?",
    "howItWorks.faq1.a": "MANAIO is primarily designed for Israeli investors looking to diversify their portfolio with international real estate. However, our platform is open to all qualified investors.",
    "howItWorks.faq2.q": "What is the minimum investment amount?",
    "howItWorks.faq2.a": "Properties on our platform start from approximately €68,000 in Georgia, with options available across all budget ranges up to premium villas exceeding €500,000.",
    "howItWorks.faq3.q": "Do I need to visit the property before investing?",
    "howItWorks.faq3.a": "While we recommend visiting when possible, many of our investors purchase remotely. We provide detailed virtual tours, comprehensive documentation, and local representatives who can visit on your behalf.",
    "howItWorks.faq4.q": "How are expected ROI figures calculated?",
    "howItWorks.faq4.a": "ROI projections are based on current market rental data, historical occupancy rates, and property management costs. These are estimates and actual returns may vary based on market conditions.",
    "howItWorks.ctaTitle": "Ready to Get Started?",
    "howItWorks.ctaSubtitle": "Browse our curated selection of international investment properties.",

    // Countries (extended)
    "countries.available": "available",
    "countries.investIn": "Invest in",
    "countries.propertiesIn": "Properties in",
    "countries.noProperties": "No properties available in {name} at the moment.",
    "countries.checkBack": "Check back soon for new listings.",
    "countries.notFound": "Country not found",
    "countries.backToCountries": "Back to Countries",

    // Chat
    "chat.sendMessage": "Send Message",
    "chat.placeholder": "Type a message...",
    "chat.noMessages": "No messages yet. Send the first message!",
    "chat.loginRequired": "Please sign in to send a message",
    "chat.agentSubtitle": "Investment Agent",
    "chat.backToChats": "Back to Chats",
    "chat.noChats": "No chats yet",
    "chat.noChatsSub": "When clients send messages, they will appear here",
    "dashboard.agent.chats": "Chats",

    // Follow & Notifications
    "agent.follow": "Follow",
    "agent.following": "Following",
    "nav.notifications": "Notifications",
    "notifications.markAllRead": "Mark all as read",
    "notifications.empty": "No notifications",
    "dashboard.buyer.favoriteAgents": "Favorite Agents",
    "dashboard.buyer.noAgents": "No favorite agents",
    "dashboard.buyer.noAgentsSub": "Follow agents from property pages to get notified about their new listings",
    "dashboard.buyer.listings": "listings",
    "dashboard.buyer.unfollow": "Unfollow",

    // Footer extras
    "footer.soon": "Soon",

    // Navbar extras
    "nav.register": "Register",
    "nav.myProperties": "My Properties",
    "auth.registerAsInvestor": "Register as Investor",
    "auth.registerAsAgent": "Register as Agent",

    // Dashboard extras
    "dashboard.buyer.reminderSent": "Reminder sent to agent",

    // Chat extras
    "chat.agent": "Agent",

    // About extras
    "about.aboutUs": "About Us",
    "about.foundersText": "The site developers wanted to create a convenient platform — not just for real estate abroad, but for the entire investment world. By making foreign brokers and the way investors operate in each country accessible, every Israeli investor can act in international real estate markets with confidence, transparency, and simplicity — without needing prior knowledge of each market.",
    "about.stat.founded": "Founded",
    "about.stat.investments": "Investments Completed",
    "about.stat.investors": "Happy Investors",
    "about.stat.countries": "Active Countries",

    // Countries extras
    "countries.comingSoon": "Coming Soon",
    "countries.launchingSoon": "Launching soon",
    "countries.stayTuned": "We're working on bringing quality investment properties in this country. Stay tuned.",
    "countries.propertiesComingSoon": "Properties in {name} — Coming Soon",

    // Property types
    "propertyType.apartment": "Apartment",
    "propertyType.villa": "Villa",
    "propertyType.condo": "Condo",
    "propertyType.studio": "Studio",
    "propertyType.penthouse": "Penthouse",
    "propertyType.house": "House",
    "propertyType.land": "Land",

    // Card price label
    "card.price": "Price",

    // Admin tabs & stats
    "admin.tab.pendingAgents": "Pending Agents",
    "admin.tab.properties": "Active Properties",
    "admin.tab.leads": "Leads",
    "admin.tab.closed": "Closed Properties",
    "admin.tab.agents": "Agents",
    "admin.tab.users": "Users",
    "admin.tab.finance": "Finance",
    "admin.stat.activeProperties": "Active Properties",
    "admin.stat.totalLeads": "Total Leads",
    "admin.stat.closedProperties": "Closed Properties",
    "admin.stat.agents": "Agents",
    "admin.accessDenied": "Access Denied",
    "admin.accessDeniedSub": "You don't have permission to access the admin panel.",
    "admin.loading": "Loading...",
    "admin.connectedAs": "Connected as:",

    // Admin form
    "admin.form.editProperty": "Edit Property",
    "admin.form.addNewProperty": "Add New Property",
    "admin.form.titleLabel": "Title",
    "admin.form.city": "City",
    "admin.form.expectedRoi": "Expected ROI (%)",
    "admin.form.bedrooms": "Bedrooms",
    "admin.form.agentName": "Agent Name",
    "admin.form.agentEmail": "Agent Email",
    "admin.form.status": "Status",
    "admin.form.statusActive": "Active",
    "admin.form.statusClosed": "Closed",
    "admin.form.premium": "⭐ Premium Property",
    "admin.form.images": "Property Images",
    "admin.form.clickToSetPrimary": "(Click image to set as primary)",
    "admin.form.addImage": "Add Image",
    "admin.form.uploading": "Uploading...",
    "admin.table.property": "Property",
    "admin.table.location": "Location",
    "admin.table.roi": "ROI",
    "admin.table.type": "Type",
    "admin.table.actions": "Actions",
    "admin.table.edit": "Edit",
    "admin.closeProperty": "Close",
    "admin.reopenProperty": "Reopen",
    "admin.noActiveProperties": "No active properties",
    "admin.noClosedProperties": "No closed properties",

    // Footer
    "footer.description": "MANAIO connects Israeli investors with premium international real estate opportunities. Explore curated properties in top global markets with transparent pricing and expert guidance.",
    "footer.quickLinks": "Quick Links",
    "footer.investmentCountries": "Investment Countries",
    "footer.contact": "Contact",
    "footer.greece": "Greece",
    "footer.cyprus": "Cyprus",
    "footer.georgia": "Georgia",
    "footer.portugal": "Portugal",
    "footer.disclaimer": "Legal Disclaimer",
    "footer.disclaimerText": "MANAIO is an information platform and does not provide financial, legal, or tax advice. All investment decisions should be made after consulting with qualified professionals. Property values, rental yields, and ROI estimates are projections based on market data and are not guaranteed. Past performance does not indicate future results.",
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",

    // Common
    "common.loading": "Loading...",
    "common.notFound": "Page Not Found",
    "common.pageNotFoundDesc": "Sorry, the page you're looking for doesn't exist or has been removed. You might find what you're looking for on these pages:",
    "common.backToHome": "Back to Home",
    "common.viewProperties": "View Properties",

    // Cookies
    "cookies.text": "We use cookies to improve your browsing experience and analyze site traffic.",
    "cookies.accept": "Accept",
    "cookies.decline": "Decline",
    "cookies.privacy": "Privacy Policy",

    // Register Agent
    "register.agent.title": "Register as Agent",
    "register.agent.subtitle": "Create an account and start listing properties",
    "register.agent.pending": "Application Submitted",
    "register.agent.pendingDesc": "Thank you for registering! Your application is being reviewed by the MANAIO team. We will get back to you within 1-2 business days after verifying your broker license and partnership agreement.",
    "register.agent.questions": "Questions? Contact us:",
    "register.agent.companyName": "Company Name",
    "register.agent.companyNamePlaceholder": "Your company name (optional)",
    "register.agent.brokerLicense": "Broker License *",
    "register.agent.idCard": "ID Card *",
    "register.agent.fileFormats": "PDF, JPG or PNG — up to 5MB",
    "register.agent.partnershipAgree": "I have read and agree to the",
    "register.agent.partnershipName": "Partnership Agreement",
    "register.agent.partnershipWith": "with MANAIO",
    "register.agent.submit": "Submit Application",
    "register.agent.investorLink": "Investor? Register here →",
    "register.agent.errorInvalidFileType": "Invalid file type. Please upload PDF or image (JPG/PNG)",
    "register.agent.errorInvalidExtension": "Invalid file extension",
    "register.agent.errorFileTooLarge": "File too large. Max size: 5MB",
    "register.agent.errorNoLicense": "Please upload your broker license",
    "register.agent.errorNoId": "Please upload your ID card",
    "register.agent.errorNoPartnership": "Please agree to the partnership agreement",

    // Register Buyer
    "register.buyer.title": "Register as Investor",
    "register.buyer.subtitle": "Create an account and discover investment opportunities",
    "register.buyer.joinTitle": "Join as an Investor",
    "register.buyer.joinSubtitle": "Discover international real estate investment opportunities with end-to-end professional guidance.",
    "register.buyer.benefit1": "Access premium investment properties in 4 countries",
    "register.buyer.benefit2": "Save favorite properties and track them",
    "register.buyer.benefit3": "Track information requests and lead status",
    "register.buyer.benefit4": "Notifications for new properties and price changes",
    "register.buyer.benefit5": "ROI calculator and property comparison tools",
    "register.buyer.termsAgree": "I have read and agree to the",
    "register.buyer.terms": "Terms of Service",
    "register.buyer.termsAnd": "and",
    "register.buyer.privacy": "Privacy Policy",
    "register.buyer.termsOf": "of MANAIO",
    "register.buyer.submit": "Register as Investor",
    "register.buyer.agentLink": "Real estate agent? Register here →",
    "register.buyer.errorTerms": "Please agree to the Terms of Service",

    // Properties search
    "properties.search": "Search by city, country, property type...",

    // Lead status labels
    "status.sent": "Sent",
    "status.in_progress": "In Progress",
    "status.answered": "Answered",
    "status.closed": "Closed",

    // Admin extended
    "admin.loadingLeads": "Loading leads...",
    "admin.noLeads": "No leads yet",
    "admin.noAgents": "No agents found",
    "admin.missing": "Missing",
    "admin.pendingApproval": "Pending Approval",
    "admin.missingDocuments": "Missing documents",
    "admin.approve": "Approve",
    "admin.reject": "Reject",
    "admin.rejectConfirm": "Are you sure you want to reject this agent?",
    "admin.brokerLicense": "Broker License",
    "admin.idCard": "ID Card",
    "admin.partnershipAgreement": "Partnership Agreement",
    "admin.partnershipApproved": "Approved",
    "admin.notSigned": "Not signed",
    "admin.loadingUsers": "Loading users...",
    "admin.noUsers": "No registered users found",
    "admin.loadingFinance": "Loading finance data...",
    "admin.pendingAgents.noPending": "No pending agent requests",
    "admin.registered": "Registered:",
    "admin.generalInquiry": "General Inquiry",

    // Admin finance
    "admin.finance.totalCharged": "Total Charged",
    "admin.finance.paid": "Paid",
    "admin.finance.pendingPayment": "Pending Payment",
    "admin.finance.agentSummary": "Summary by Agent",
    "admin.finance.paymentDetails": "Payment Details",
    "admin.finance.exportCSV": "Export CSV",
    "admin.finance.addPayment": "Add Payment",
    "admin.finance.addPaymentTitle": "Add Payment / Commission",
    "admin.finance.agent": "Agent",
    "admin.finance.selectAgent": "Select agent...",
    "admin.finance.type": "Type",
    "admin.finance.leadFee": "Lead Fee",
    "admin.finance.commission": "Commission",
    "admin.finance.bonus": "Bonus",
    "admin.finance.amount": "Amount (₪)",
    "admin.finance.relatedLead": "Related Lead (optional)",
    "admin.finance.noSpecificLead": "No specific lead",
    "admin.finance.notes": "Notes",
    "admin.finance.notesPlaceholder": "Any note...",
    "admin.finance.saving": "Saving...",
    "admin.finance.noPayments": "No payments yet",
    "admin.finance.markPaid": "Mark as Paid",
    "admin.finance.pending": "Pending",
    "admin.finance.leads": "Leads",
    "admin.finance.totalOwed": "Total Owed",
    "admin.finance.balance": "Balance",
    "admin.finance.deletePayment": "Delete",
    "admin.finance.deleteConfirm": "Delete this payment?",
    "admin.finance.amountLabel": "Amount",
    "admin.finance.status": "Status",
    "admin.finance.notesCol": "Notes",
    "admin.finance.dateCol": "Date",
    "admin.finance.actionsCol": "Actions",

    // Admin table headers
    "admin.leads.name": "Name",
    "admin.leads.email": "Email",
    "admin.leads.phone": "Phone",
    "admin.leads.budget": "Budget",
    "admin.leads.property": "Property",
    "admin.leads.message": "Message",
    "admin.leads.date": "Date",
    "admin.agents.agent": "Agent",
    "admin.agents.country": "Country",
    "admin.agents.city": "City",
    "admin.agents.properties": "Properties",
    "admin.users.role": "Role",
    "admin.users.joined": "Joined",

    // Dashboard agent form sections
    "dashboard.agent.basicDetails": "Basic Details",
    "dashboard.agent.priceReturns": "Price & Returns",
    "dashboard.agent.propertySpecs": "Property Specs",
    "dashboard.agent.amenitiesLabel": "Amenities",
    "dashboard.agent.neighborhood": "Neighborhood",
    "dashboard.agent.addExpectedRoi": "Add Expected ROI (%)",
    "dashboard.agent.bathrooms": "Bathrooms",
    "dashboard.agent.areaSqm": "Area (sqm)",
    "dashboard.agent.floor": "Floor",
    "dashboard.agent.yearBuilt": "Year Built",
    "dashboard.agent.furnished": "Furnished",
    "dashboard.agent.propertyImages": "Property Images",
    "dashboard.agent.clickToSetPrimary": "Click an image to set it as primary (★ = primary)",
    "dashboard.agent.addImageBtn": "Add Image",
    "dashboard.agent.imageFormats": "JPG, PNG, WEBP — multiple files allowed",
    "dashboard.agent.uploading": "Uploading images...",
    "dashboard.agent.applicationReview": "Your Application is Under Review",
    "dashboard.agent.pendingDesc": "Thank you for registering! The MANAIO team is reviewing your broker license and partnership agreement. You will receive an email once your account is approved (usually within 1-2 business days).",
    "dashboard.agent.waitingApproval": "Waiting for approval — page will update automatically",
    "dashboard.agent.questions": "Questions?",
  },
  el: elTranslations,
  ru: ruTranslations,
  ar: arTranslations,
};

const VALID_LANGS: Lang[] = ["he", "en", "el", "ru", "ar"];

const LanguageContext = createContext<LanguageContextType>({
  lang: "he",
  setLang: () => {},
  t: (key: string) => key,
  dir: "rtl",
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("he");

  useEffect(() => {
    const stored = localStorage.getItem("manaio_lang") as Lang | null;
    if (stored && VALID_LANGS.includes(stored)) {
      setLangState(stored);
    }
  }, []);

  const setLang = (newLang: Lang) => {
    setLangState(newLang);
    localStorage.setItem("manaio_lang", newLang);
  };

  // For el/ru/ar, fall back to English if key not found
  const t = (key: string) => {
    const val = translations[lang]?.[key];
    if (val) return val;
    if (lang === "el" || lang === "ru" || lang === "ar") {
      return translations["en"][key] || key;
    }
    return key;
  };
  const dir: "rtl" | "ltr" = lang === "he" || lang === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
